### ISSUE TITLE
Improve Error messages

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-py#26]
There's a number of errors that can occur while using the client. For ever error message, we'd like to apply the following heuristic:
* Is it informative?
* Does it point the user to an action?

@dvenprasad has offered to apply this heuristic to every error message and let us know how we can improve them!

@samuel-tate could you prepare a list of error messages that can happen (with a bit of context) so she can take a look at it?

This would also be a good opportunity to add troubleshooting tips to the error messages!

**Comment by samuel-tate** [comment]
# pyrefinebio errors

@dvenprasad 
This is a compilation of what I think would be the most common errors that users would get.
Each error has the python code I wrote to get the error and the error output that I got when I tried to run the code.
Lmk if you have any questions!

## Using invalid search filters

```python
import pyrefinebio

pyrefinebio.Sample.search(foo="bar")
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.refine.bio/v1/samples/?foo=bar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.Sample.search(foo="bar")
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/sample.py", line 197, in search
    response = get_by_endpoint("samples", params=kwargs)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 68, in get_by_endpoint
    return get(url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 54, in get
    return request("GET", url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 40, in request
    raise error
pyrefinebio.exceptions.InvalidFilters: You have provided invalid filters: ['foo']
```

</p>
</details>

## Using invalid types for search filters

```python
import pyrefinebio

pyrefinebio.Sample.search(age="foo")
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.refine.bio/v1/samples/?age=foo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.Sample.search(age="foo")
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/sample.py", line 197, in search
    response = get_by_endpoint("samples", params=kwargs)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 68, in get_by_endpoint
    return get(url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 54, in get
    return request("GET", url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 40, in request
    raise error
pyrefinebio.exceptions.InvalidFilterType: You have provided invalid type for the filter, age - Enter a number.
```

</p>
</details>

## Multiple errors

```python
import pyrefinebio

pyrefinebio.Sample.search(age="foo", organism="bar")
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.refine.bio/v1/samples/?age=foo&organism=bar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.Sample.search(age="foo", organism="bar")
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/sample.py", line 197, in search
    response = get_by_endpoint("samples", params=kwargs)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 68, in get_by_endpoint
    return get(url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 54, in get
    return request("GET", url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 40, in request
    raise error
pyrefinebio.exceptions.MultipleErrors: Multiple errors have occurred:
You have provided invalid type for the filter, organism - Select a valid choice. That choice is not one of the available choices.
You have provided invalid type for the filter, age - Enter a number.
```

</p>
</details>

## 404 error

```python
import pyrefinebio

pyrefinebio.Sample.get("foo")
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.refine.bio/v1/samples/foo/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.Sample.get("foo")
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/sample.py", line 128, in get
    response = get_by_endpoint("samples/" + accession_code).json()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 68, in get_by_endpoint
    return get(url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 54, in get
    return request("GET", url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 43, in request
    raise NotFound(response.url)
pyrefinebio.exceptions.NotFound: The requested resource at https://api.refine.bio/v1/samples/foo/ was not found
```

</p>
</details>

## Setting up a Dataset with invalid data

```python
import pyrefinebio

pyrefinebio.Dataset(data={"foo": "bar"}).save()
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.refine.bio/v1/dataset/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.Dataset(data={"foo": "bar"}).save()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/dataset.py", line 189, in save
    response = post_by_endpoint("dataset", payload=body).json()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 74, in post_by_endpoint
    return post(url, payload=payload)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 58, in post
    return request("POST", url, payload=payload)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 40, in request
    raise error
pyrefinebio.exceptions.InvalidData: `data` must be a dict of lists. Problem with `foo`
```

</p>
</details>

## Downloading a dataset with `dataset_dict` AND `experiments`

```python
import pyrefinebio

pyrefinebio.download_dataset(
    "./test.zip",
    "foo@bar.com",
    dataset_dict={"GSE74410": ["GSM1919903"]},
    experiments=["GSE107458"]
)
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pyrefinebio.download_dataset("./test.zip", "foo@bar.com", dataset_dict={"GSE74410": "GSM1919903"}, experiments=["GSE107458"])
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/high_level_functions.py", line 94, in download_dataset
    raise DownloadError(
pyrefinebio.exceptions.DownloadError: Unable to download Dataset
You should either provide dataset_dict or experiments but not both
```

</p>
</details>


## Trying to download a Dataset with an Experiment that has no downloadable Samples

```python
import pyrefinebio

exs = pyrefinebio.Experiment.search(num_downloadable_samples=0)

pyrefinebio.download_dataset(
    "./test.zip",
    "foo@bar.com",
    experiments=[exs[0]]
)
```

<details>
<summary>error output</summary>
<p>

```
creating dataset...
done!
processing dataset...
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.refine.bio/v1/dataset/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    pyrefinebio.download_dataset(
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/high_level_functions.py", line 116, in download_dataset
    dataset.process()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/dataset.py", line 211, in process
    response = self.save()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/dataset.py", line 189, in save
    response = post_by_endpoint("dataset", payload=body).json()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 74, in post_by_endpoint
    return post(url, payload=payload)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 58, in post
    return request("POST", url, payload=payload)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 40, in request
    raise error
pyrefinebio.exceptions.InvalidData: Experiment(s) in dataset have zero downloadable samples. See `details` for a full list
Details: ['SRP150473']
```

</p>
</details>

## Trying to download a Dataset without a valid token

```python
import pyrefinebio

# set the token to nonsense
token = pyrefinebio.Token.get_token()
pyrefinebio.config.Config().token = "foo"

# try to download a Dataset
try:
    dataset = pyrefinebio.Dataset.get("16d91ede-680d-47dc-a023-2ac6ff28354e")
    dataset.download("./test.zip")
finally:
    # reset the token
    token.save_token()
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    dataset.download("./test.zip")
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/dataset.py", line 240, in download
    raise DownloadError("dataset", "Download url not found - did you process the dataset?")
pyrefinebio.exceptions.DownloadError: Unable to download dataset
Download url not found - did you process the dataset?
```

The error assumes that it can't find the download url because the Dataset wasn't processed, which in this case is incorrect.
In this case the download url wasn't found because we aren't using an activated token.
We could probably add some logic to figure out the reason for the download url being missing.

</p>
</details>


## Trying to save a token with an invalid id

```python
import pyrefinebio

token = pyrefinebio.Token(id="foo").save_token()
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 30, in request
    response.raise_for_status()
  File "/Users/state/Documents/repos/refinebio-py/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.refine.bio/v1/token/foo/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/token.py", line 84, in save_token
    response = get_by_endpoint("token/" + str(self.id)).json()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 68, in get_by_endpoint
    return get(url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 54, in get
    return request("GET", url, params=params)
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/http.py", line 43, in request
    raise NotFound(response.url)
pyrefinebio.exceptions.NotFound: The requested resource at https://api.refine.bio/v1/token/foo/ was not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    token = pyrefinebio.Token(id="foo").save_token()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/token.py", line 91, in save_token
    raise BadRequest(
pyrefinebio.exceptions.BadRequest: Bad Request: Token with id 'foo' does not exist in RefineBio. Please create a new token.
```

</p>
</details>

## Trying to save a Token without agreeing to the terms and conditions

```python
import pyrefinebio

token = pyrefinebio.Token().save_token()
```

<details>
<summary>error output</summary>
<p>

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    token = pyrefinebio.Token().save_token()
  File "/Users/state/Documents/repos/refinebio-py/pyrefinebio/token.py", line 86, in save_token
    raise BadRequest(
pyrefinebio.exceptions.BadRequest: Bad Request: Token with id '6ef82eb2-7a25-46f0-8da9-52cd03b2284b' is not activated. Please activate your token with `agree_to_terms_and_conditions()` before saving it.
```

</p>
</details>

**Comment by dvenprasad** [comment]
Okay, I have both question and recommendations. Questions first

## **Questions**

- `Setting up a Dataset with invalid data` Can I get more information about the data_dict and experiment arguments? When would a user use data_dict vs experiment argument? 

- Setting up a Dataset with invalid data



## **Recommendations 🥁** 

### Using invalid search filters

`pyrefinebio.exceptions.InvalidFilters: You have provided invalid filters: ['foo']`

→ Add `See documentation for a list of valid filters` (and if we don't have it in docs, we should add it) 

### Using invalid types for search filters

For organisms, can we say use <function>( I think it is `Organism.search()` ) for a list of valid organisms in the error message. 

Sidebar: `Organism.search()` implies that they can search the list, which is not true. Could it be `Organism.list()` instead?


### Trying to download a Dataset with an Experiment that has no downloadable Samples

The error message itself is good.  We should mention that they can request for these experiments on [refine.bio](http://refine.bio) for now. 

Also what you think of having them make requests for experiments via the client? If they have a whole list of experiments, it may be easier for them to answer our questions once, instead of doing it for each experiment? But also downside is that, they can bulk request experiments without really considering them. So maybe that friction is good. Would love a dev perspective on this. (tagging @jaclyn-taroni @kurtwheeler for their perspective too) 

### Trying to download a Dataset without a valid token

> The error assumes that it can't find the download url because the Dataset wasn't processed, which in this case is incorrect.In this case the download url wasn't found because we aren't using an activated token.We could probably add some logic to figure out the reason for the download url being missing.

Yeah we should implement that logic to check if it is a token error. Then we should tell them how to get it. (ideally the high level function to get a token, which will just walk them through the whole thing and say for see documentation for advanced usage) 

### Trying to save a token with an invalid id

`pyrefinebio.exceptions.BadRequest: Bad Request: Token with id 'foo' does not exist in RefineBio. Please create a new token.` 

Here, can we say `Please create new token using <function>` ?

General comment, we should always refer to refinebio as `refine.bio` with lower case r (Yes, all the time. Yes, even if it is at the beginning of a sentence) in documentation and messages.

**Comment by samuel-tate** [comment]
@dvenprasad 
Created a PR which addressed a lot of the recommendations that you gave - #41 

I think we addressed the 2 questions during the sprint meeting.

But, also, for the search() terminology - I think of it as in the users are searching for Samples or Organisms based on some filters that they can pass in.
like if they were looking for Samples for a certain organism they could do `pyrefinebio.Sample.search(organism="danio_rerio")`
I'm not sure if that makes sense, but I've kind of gotten used to it.
We could always switch to `.list()` though - I think it would just be a lot of find and replace.
lmk what you think.

**Comment by dvenprasad** [comment]
Ah I see... in the context of samples, `Search()` makes complete sense. 

Maybe I should back up a little bit and clarify the assumptions I may have made 😅  

For `Organism.Search()` function, can users use a keyword to search? i.e are they filters available like for `Sample.search(organism="danio_rerio")` ?

**Comment by samuel-tate** [comment]
For Organism, not really because the refine.bio api endpoint `/organisms/` doesn't have any filters right now.
It always will return a paginated list of all the organisms.
I'm actually adding some filters to it right now though so it will have some in the future.
There are some other endpoints that have no filters still though.

**Comment by dvenprasad** [comment]
Ah cool.. in that case, we should note in documentation that `Organism.Search()` without any filters will return the full list of organism.
