### ISSUE TITLE
unexpected keyword argument 'genetic_information'

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-py#85]
Trying to access sample information with `pyrefinebio.Sample.get()` results in an error at initialization, presumably due to changes in the API return values...

Example interaction:
```
>>> pyrefinebio.Sample.get("GSM604809")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/josh/.conda/envs/rb-collector/lib/python3.11/site-packages/pyrefinebio/sample.py", line 165, in get
    return cls(**response)
           ^^^^^^^^^^^^^^^
TypeError: Sample.__init__() got an unexpected keyword argument 'genetic_information'
```

**Comment by jashapiro** [comment]
closed by #86
